'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSRendicion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSRendicion.RendicionSoap")>  _
    Public Interface RendicionSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EnviarRendicion", ReplyAction:="*")>  _
        Function EnviarRendicion(ByVal request As WSRendicion.EnviarRendicionRequest) As WSRendicion.EnviarRendicionResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarRendicionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarRendicion", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRendicion.EnviarRendicionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRendicion.EnviarRendicionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarRendicionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NroRendicion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public IdViajante As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public F_Rendicion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Observaciones As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Efectivo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Dolares As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Euros As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public ChequesCant As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public ChequesMonto As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public CertificadosCant As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=11)>  _
        Public CertificadosMonto As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=12)>  _
        Public DetalleValores As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=13)>  _
        Public DetalleRecibos As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal NroRendicion As String, ByVal IdViajante As String, ByVal F_Rendicion As String, ByVal Observaciones As String, ByVal Efectivo As String, ByVal Dolares As String, ByVal Euros As String, ByVal ChequesCant As String, ByVal ChequesMonto As String, ByVal CertificadosCant As String, ByVal CertificadosMonto As String, ByVal DetalleValores As String, ByVal DetalleRecibos As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.NroRendicion = NroRendicion
            Me.IdViajante = IdViajante
            Me.F_Rendicion = F_Rendicion
            Me.Observaciones = Observaciones
            Me.Efectivo = Efectivo
            Me.Dolares = Dolares
            Me.Euros = Euros
            Me.ChequesCant = ChequesCant
            Me.ChequesMonto = ChequesMonto
            Me.CertificadosCant = CertificadosCant
            Me.CertificadosMonto = CertificadosMonto
            Me.DetalleValores = DetalleValores
            Me.DetalleRecibos = DetalleRecibos
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarRendicionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarRendicionResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRendicion.EnviarRendicionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRendicion.EnviarRendicionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarRendicionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public EnviarRendicionResult As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EnviarRendicionResult As Long)
            MyBase.New
            Me.EnviarRendicionResult = EnviarRendicionResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface RendicionSoapChannel
        Inherits WSRendicion.RendicionSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class RendicionSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSRendicion.RendicionSoap)
        Implements WSRendicion.RendicionSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRendicion_RendicionSoap_EnviarRendicion(ByVal request As WSRendicion.EnviarRendicionRequest) As WSRendicion.EnviarRendicionResponse Implements WSRendicion.RendicionSoap.EnviarRendicion
            Return MyBase.Channel.EnviarRendicion(request)
        End Function
        
        Public Function EnviarRendicion(ByVal MacAddress As String, ByVal NroRendicion As String, ByVal IdViajante As String, ByVal F_Rendicion As String, ByVal Observaciones As String, ByVal Efectivo As String, ByVal Dolares As String, ByVal Euros As String, ByVal ChequesCant As String, ByVal ChequesMonto As String, ByVal CertificadosCant As String, ByVal CertificadosMonto As String, ByVal DetalleValores As String, ByVal DetalleRecibos As String) As Long
            Dim inValue As WSRendicion.EnviarRendicionRequest = New WSRendicion.EnviarRendicionRequest()
            inValue.Body = New WSRendicion.EnviarRendicionRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.NroRendicion = NroRendicion
            inValue.Body.IdViajante = IdViajante
            inValue.Body.F_Rendicion = F_Rendicion
            inValue.Body.Observaciones = Observaciones
            inValue.Body.Efectivo = Efectivo
            inValue.Body.Dolares = Dolares
            inValue.Body.Euros = Euros
            inValue.Body.ChequesCant = ChequesCant
            inValue.Body.ChequesMonto = ChequesMonto
            inValue.Body.CertificadosCant = CertificadosCant
            inValue.Body.CertificadosMonto = CertificadosMonto
            inValue.Body.DetalleValores = DetalleValores
            inValue.Body.DetalleRecibos = DetalleRecibos
            Dim retVal As WSRendicion.EnviarRendicionResponse = CType(Me,WSRendicion.RendicionSoap).EnviarRendicion(inValue)
            Return retVal.Body.EnviarRendicionResult
        End Function
    End Class
End Namespace
