'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSPedidos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSPedidos.PedidosSoap")>  _
    Public Interface PedidosSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EnviarPedido7", ReplyAction:="*")>  _
        Function EnviarPedido7(ByVal request As WSPedidos.EnviarPedido7Request) As WSPedidos.EnviarPedido7Response
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarPedido7Request
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarPedido7", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSPedidos.EnviarPedido7RequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSPedidos.EnviarPedido7RequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarPedido7RequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NroPedido As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public CodCliente As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Fecha As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Observaciones As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Transporte As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Detalle As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal NroPedido As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Transporte As String, ByVal Detalle As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.NroPedido = NroPedido
            Me.CodCliente = CodCliente
            Me.Fecha = Fecha
            Me.Observaciones = Observaciones
            Me.Transporte = Transporte
            Me.Detalle = Detalle
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarPedido7Response
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarPedido7Response", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSPedidos.EnviarPedido7ResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSPedidos.EnviarPedido7ResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarPedido7ResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public EnviarPedido7Result As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EnviarPedido7Result As Long)
            MyBase.New
            Me.EnviarPedido7Result = EnviarPedido7Result
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface PedidosSoapChannel
        Inherits WSPedidos.PedidosSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class PedidosSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSPedidos.PedidosSoap)
        Implements WSPedidos.PedidosSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSPedidos_PedidosSoap_EnviarPedido7(ByVal request As WSPedidos.EnviarPedido7Request) As WSPedidos.EnviarPedido7Response Implements WSPedidos.PedidosSoap.EnviarPedido7
            Return MyBase.Channel.EnviarPedido7(request)
        End Function
        
        Public Function EnviarPedido7(ByVal MacAddress As String, ByVal NroPedido As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Transporte As String, ByVal Detalle As String) As Long
            Dim inValue As WSPedidos.EnviarPedido7Request = New WSPedidos.EnviarPedido7Request()
            inValue.Body = New WSPedidos.EnviarPedido7RequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.NroPedido = NroPedido
            inValue.Body.CodCliente = CodCliente
            inValue.Body.Fecha = Fecha
            inValue.Body.Observaciones = Observaciones
            inValue.Body.Transporte = Transporte
            inValue.Body.Detalle = Detalle
            Dim retVal As WSPedidos.EnviarPedido7Response = CType(Me,WSPedidos.PedidosSoap).EnviarPedido7(inValue)
            Return retVal.Body.EnviarPedido7Result
        End Function
    End Class
End Namespace
