'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
'
Namespace InterDepositoWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="InterDepositoSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class InterDeposito
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarInterDepositoOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CatalogoLibraryVB.My.MySettings.Default.CatalogoLibraryVB_InterDepositoWS_InterDeposito
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarInterDepositoCompleted As EnviarInterDepositoCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarInterDeposito", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarInterDeposito(ByVal MacAddress As String, ByVal NroInterDeposito As String, ByVal CodCliente As String, ByVal Bco_Dep_Tipo As String, ByVal Bco_Dep_Fecha As String, ByVal Bco_Dep_Numero As String, ByVal Bco_Dep_Monto As String, ByVal Bco_Dep_Ch_Cantidad As String, ByVal Bco_Dep_IdCta As String, ByVal Observaciones As String, ByVal Detalle As String) As Long
            Dim results() As Object = Me.Invoke("EnviarInterDeposito", New Object() {MacAddress, NroInterDeposito, CodCliente, Bco_Dep_Tipo, Bco_Dep_Fecha, Bco_Dep_Numero, Bco_Dep_Monto, Bco_Dep_Ch_Cantidad, Bco_Dep_IdCta, Observaciones, Detalle})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarInterDepositoAsync(ByVal MacAddress As String, ByVal NroInterDeposito As String, ByVal CodCliente As String, ByVal Bco_Dep_Tipo As String, ByVal Bco_Dep_Fecha As String, ByVal Bco_Dep_Numero As String, ByVal Bco_Dep_Monto As String, ByVal Bco_Dep_Ch_Cantidad As String, ByVal Bco_Dep_IdCta As String, ByVal Observaciones As String, ByVal Detalle As String)
            Me.EnviarInterDepositoAsync(MacAddress, NroInterDeposito, CodCliente, Bco_Dep_Tipo, Bco_Dep_Fecha, Bco_Dep_Numero, Bco_Dep_Monto, Bco_Dep_Ch_Cantidad, Bco_Dep_IdCta, Observaciones, Detalle, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarInterDepositoAsync(ByVal MacAddress As String, ByVal NroInterDeposito As String, ByVal CodCliente As String, ByVal Bco_Dep_Tipo As String, ByVal Bco_Dep_Fecha As String, ByVal Bco_Dep_Numero As String, ByVal Bco_Dep_Monto As String, ByVal Bco_Dep_Ch_Cantidad As String, ByVal Bco_Dep_IdCta As String, ByVal Observaciones As String, ByVal Detalle As String, ByVal userState As Object)
            If (Me.EnviarInterDepositoOperationCompleted Is Nothing) Then
                Me.EnviarInterDepositoOperationCompleted = AddressOf Me.OnEnviarInterDepositoOperationCompleted
            End If
            Me.InvokeAsync("EnviarInterDeposito", New Object() {MacAddress, NroInterDeposito, CodCliente, Bco_Dep_Tipo, Bco_Dep_Fecha, Bco_Dep_Numero, Bco_Dep_Monto, Bco_Dep_Ch_Cantidad, Bco_Dep_IdCta, Observaciones, Detalle}, Me.EnviarInterDepositoOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarInterDepositoOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarInterDepositoCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarInterDepositoCompleted(Me, New EnviarInterDepositoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub EnviarInterDepositoCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarInterDepositoCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarInterDepositoCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
End Namespace
