'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSCatalogo
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSCatalogo.InfoSoap")>  _
    Public Interface InfoSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIp", ReplyAction:="*")>  _
        Function GetIp(ByVal request As WSCatalogo.GetIpRequest) As WSCatalogo.GetIpResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SetIp", ReplyAction:="*")>  _
        Function SetIp(ByVal request As WSCatalogo.SetIpRequest) As WSCatalogo.SetIpResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIpIntranet", ReplyAction:="*")>  _
        Function GetIpIntranet(ByVal request As WSCatalogo.GetIpIntranetRequest) As WSCatalogo.GetIpIntranetResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SetIpIntranet", ReplyAction:="*")>  _
        Function SetIpIntranet(ByVal request As WSCatalogo.SetIpIntranetRequest) As WSCatalogo.SetIpIntranetResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetIpCatalogo", ReplyAction:="*")>  _
        Function GetIpCatalogo(ByVal request As WSCatalogo.GetIpCatalogoRequest) As WSCatalogo.GetIpCatalogoResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SetIpCatalogo", ReplyAction:="*")>  _
        Function SetIpCatalogo(ByVal request As WSCatalogo.SetIpCatalogoRequest) As WSCatalogo.SetIpCatalogoResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIpRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIp", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.GetIpRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.GetIpRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetIpRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String)
            MyBase.New
            Me.MacAddress = MacAddress
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIpResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIpResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.GetIpResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.GetIpResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetIpResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetIpResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetIpResult As String)
            MyBase.New
            Me.GetIpResult = GetIpResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetIpRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetIp", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.SetIpRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.SetIpRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetIpRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NewURL As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal NewURL As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.NewURL = NewURL
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetIpResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetIpResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.SetIpResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.SetIpResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetIpResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public SetIpResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SetIpResult As Boolean)
            MyBase.New
            Me.SetIpResult = SetIpResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIpIntranetRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIpIntranet", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.GetIpIntranetRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.GetIpIntranetRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetIpIntranetRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String)
            MyBase.New
            Me.MacAddress = MacAddress
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIpIntranetResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIpIntranetResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.GetIpIntranetResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.GetIpIntranetResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetIpIntranetResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetIpIntranetResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetIpIntranetResult As String)
            MyBase.New
            Me.GetIpIntranetResult = GetIpIntranetResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetIpIntranetRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetIpIntranet", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.SetIpIntranetRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.SetIpIntranetRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetIpIntranetRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NewURL As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal NewURL As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.NewURL = NewURL
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetIpIntranetResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetIpIntranetResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.SetIpIntranetResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.SetIpIntranetResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetIpIntranetResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public SetIpIntranetResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SetIpIntranetResult As Boolean)
            MyBase.New
            Me.SetIpIntranetResult = SetIpIntranetResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIpCatalogoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIpCatalogo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.GetIpCatalogoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.GetIpCatalogoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetIpCatalogoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String)
            MyBase.New
            Me.MacAddress = MacAddress
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetIpCatalogoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetIpCatalogoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.GetIpCatalogoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.GetIpCatalogoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetIpCatalogoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetIpCatalogoResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetIpCatalogoResult As String)
            MyBase.New
            Me.GetIpCatalogoResult = GetIpCatalogoResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetIpCatalogoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetIpCatalogo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.SetIpCatalogoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.SetIpCatalogoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetIpCatalogoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NewURL As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal NewURL As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.NewURL = NewURL
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class SetIpCatalogoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="SetIpCatalogoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSCatalogo.SetIpCatalogoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSCatalogo.SetIpCatalogoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class SetIpCatalogoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public SetIpCatalogoResult As Boolean
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal SetIpCatalogoResult As Boolean)
            MyBase.New
            Me.SetIpCatalogoResult = SetIpCatalogoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface InfoSoapChannel
        Inherits WSCatalogo.InfoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InfoSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSCatalogo.InfoSoap)
        Implements WSCatalogo.InfoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCatalogo_InfoSoap_GetIp(ByVal request As WSCatalogo.GetIpRequest) As WSCatalogo.GetIpResponse Implements WSCatalogo.InfoSoap.GetIp
            Return MyBase.Channel.GetIp(request)
        End Function
        
        Public Function GetIp(ByVal MacAddress As String) As String
            Dim inValue As WSCatalogo.GetIpRequest = New WSCatalogo.GetIpRequest()
            inValue.Body = New WSCatalogo.GetIpRequestBody()
            inValue.Body.MacAddress = MacAddress
            Dim retVal As WSCatalogo.GetIpResponse = CType(Me,WSCatalogo.InfoSoap).GetIp(inValue)
            Return retVal.Body.GetIpResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCatalogo_InfoSoap_SetIp(ByVal request As WSCatalogo.SetIpRequest) As WSCatalogo.SetIpResponse Implements WSCatalogo.InfoSoap.SetIp
            Return MyBase.Channel.SetIp(request)
        End Function
        
        Public Function SetIp(ByVal MacAddress As String, ByVal NewURL As String) As Boolean
            Dim inValue As WSCatalogo.SetIpRequest = New WSCatalogo.SetIpRequest()
            inValue.Body = New WSCatalogo.SetIpRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.NewURL = NewURL
            Dim retVal As WSCatalogo.SetIpResponse = CType(Me,WSCatalogo.InfoSoap).SetIp(inValue)
            Return retVal.Body.SetIpResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCatalogo_InfoSoap_GetIpIntranet(ByVal request As WSCatalogo.GetIpIntranetRequest) As WSCatalogo.GetIpIntranetResponse Implements WSCatalogo.InfoSoap.GetIpIntranet
            Return MyBase.Channel.GetIpIntranet(request)
        End Function
        
        Public Function GetIpIntranet(ByVal MacAddress As String) As String
            Dim inValue As WSCatalogo.GetIpIntranetRequest = New WSCatalogo.GetIpIntranetRequest()
            inValue.Body = New WSCatalogo.GetIpIntranetRequestBody()
            inValue.Body.MacAddress = MacAddress
            Dim retVal As WSCatalogo.GetIpIntranetResponse = CType(Me,WSCatalogo.InfoSoap).GetIpIntranet(inValue)
            Return retVal.Body.GetIpIntranetResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCatalogo_InfoSoap_SetIpIntranet(ByVal request As WSCatalogo.SetIpIntranetRequest) As WSCatalogo.SetIpIntranetResponse Implements WSCatalogo.InfoSoap.SetIpIntranet
            Return MyBase.Channel.SetIpIntranet(request)
        End Function
        
        Public Function SetIpIntranet(ByVal MacAddress As String, ByVal NewURL As String) As Boolean
            Dim inValue As WSCatalogo.SetIpIntranetRequest = New WSCatalogo.SetIpIntranetRequest()
            inValue.Body = New WSCatalogo.SetIpIntranetRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.NewURL = NewURL
            Dim retVal As WSCatalogo.SetIpIntranetResponse = CType(Me,WSCatalogo.InfoSoap).SetIpIntranet(inValue)
            Return retVal.Body.SetIpIntranetResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCatalogo_InfoSoap_GetIpCatalogo(ByVal request As WSCatalogo.GetIpCatalogoRequest) As WSCatalogo.GetIpCatalogoResponse Implements WSCatalogo.InfoSoap.GetIpCatalogo
            Return MyBase.Channel.GetIpCatalogo(request)
        End Function
        
        Public Function GetIpCatalogo(ByVal MacAddress As String) As String
            Dim inValue As WSCatalogo.GetIpCatalogoRequest = New WSCatalogo.GetIpCatalogoRequest()
            inValue.Body = New WSCatalogo.GetIpCatalogoRequestBody()
            inValue.Body.MacAddress = MacAddress
            Dim retVal As WSCatalogo.GetIpCatalogoResponse = CType(Me,WSCatalogo.InfoSoap).GetIpCatalogo(inValue)
            Return retVal.Body.GetIpCatalogoResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSCatalogo_InfoSoap_SetIpCatalogo(ByVal request As WSCatalogo.SetIpCatalogoRequest) As WSCatalogo.SetIpCatalogoResponse Implements WSCatalogo.InfoSoap.SetIpCatalogo
            Return MyBase.Channel.SetIpCatalogo(request)
        End Function
        
        Public Function SetIpCatalogo(ByVal MacAddress As String, ByVal NewURL As String) As Boolean
            Dim inValue As WSCatalogo.SetIpCatalogoRequest = New WSCatalogo.SetIpCatalogoRequest()
            inValue.Body = New WSCatalogo.SetIpCatalogoRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.NewURL = NewURL
            Dim retVal As WSCatalogo.SetIpCatalogoResponse = CType(Me,WSCatalogo.InfoSoap).SetIpCatalogo(inValue)
            Return retVal.Body.SetIpCatalogoResult
        End Function
    End Class
End Namespace
