'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
'
Namespace RecibosWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="Recibos_v_303Soap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Recibos_v_303
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarReciboOperationCompleted As System.Threading.SendOrPostCallback
        
        Private EnviarRecibo317OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CatalogoLibraryVB.My.MySettings.Default.CatalogoLibraryVB_RecibosWS_Recibos_v_303
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarReciboCompleted As EnviarReciboCompletedEventHandler
        
        '''<remarks/>
        Public Event EnviarRecibo317Completed As EnviarRecibo317CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarRecibo", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarRecibo(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String) As Long
            Dim results() As Object = Me.Invoke("EnviarRecibo", New Object() {MacAddress, NroRecibo, CodCliente, Fecha, Bahia, Total, Detalle, Facturas})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarReciboAsync(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String)
            Me.EnviarReciboAsync(MacAddress, NroRecibo, CodCliente, Fecha, Bahia, Total, Detalle, Facturas, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarReciboAsync(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String, ByVal userState As Object)
            If (Me.EnviarReciboOperationCompleted Is Nothing) Then
                Me.EnviarReciboOperationCompleted = AddressOf Me.OnEnviarReciboOperationCompleted
            End If
            Me.InvokeAsync("EnviarRecibo", New Object() {MacAddress, NroRecibo, CodCliente, Fecha, Bahia, Total, Detalle, Facturas}, Me.EnviarReciboOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarReciboOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarReciboCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarReciboCompleted(Me, New EnviarReciboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarRecibo317", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarRecibo317(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String, ByVal NotasCredito As String) As Long
            Dim results() As Object = Me.Invoke("EnviarRecibo317", New Object() {MacAddress, NroRecibo, CodCliente, Fecha, Bahia, Total, Detalle, Facturas, NotasCredito})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarRecibo317Async(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String, ByVal NotasCredito As String)
            Me.EnviarRecibo317Async(MacAddress, NroRecibo, CodCliente, Fecha, Bahia, Total, Detalle, Facturas, NotasCredito, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarRecibo317Async(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String, ByVal NotasCredito As String, ByVal userState As Object)
            If (Me.EnviarRecibo317OperationCompleted Is Nothing) Then
                Me.EnviarRecibo317OperationCompleted = AddressOf Me.OnEnviarRecibo317OperationCompleted
            End If
            Me.InvokeAsync("EnviarRecibo317", New Object() {MacAddress, NroRecibo, CodCliente, Fecha, Bahia, Total, Detalle, Facturas, NotasCredito}, Me.EnviarRecibo317OperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarRecibo317OperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarRecibo317CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarRecibo317Completed(Me, New EnviarRecibo317CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub EnviarReciboCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarReciboCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarReciboCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub EnviarRecibo317CompletedEventHandler(ByVal sender As Object, ByVal e As EnviarRecibo317CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarRecibo317CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
End Namespace
