'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSLlaveCliente
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSLlaveCliente.LLaveClienteSoap")>  _
    Public Interface LLaveClienteSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtenerListaPrecio", ReplyAction:="*")>  _
        Function ObtenerListaPrecio(ByVal request As WSLlaveCliente.ObtenerListaPrecioRequest) As WSLlaveCliente.ObtenerListaPrecioResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtenerEstadoActual", ReplyAction:="*")>  _
        Function ObtenerEstadoActual(ByVal request As WSLlaveCliente.ObtenerEstadoActualRequest) As WSLlaveCliente.ObtenerEstadoActualResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento IdViajante del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtenerLLaveViajante", ReplyAction:="*")>  _
        Function ObtenerLLaveViajante(ByVal request As WSLlaveCliente.ObtenerLLaveViajanteRequest) As WSLlaveCliente.ObtenerLLaveViajanteResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ObtenerLLaveCatalogo", ReplyAction:="*")>  _
        Function ObtenerLLaveCatalogo(ByVal request As WSLlaveCliente.ObtenerLLaveCatalogoRequest) As WSLlaveCliente.ObtenerLLaveCatalogoResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerListaPrecioRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerListaPrecio", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSLlaveCliente.ObtenerListaPrecioRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSLlaveCliente.ObtenerListaPrecioRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerListaPrecioRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Cuit As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public IDAns As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal Cuit As String, ByVal IDAns As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.Cuit = Cuit
            Me.IDAns = IDAns
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerListaPrecioResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerListaPrecioResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSLlaveCliente.ObtenerListaPrecioResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSLlaveCliente.ObtenerListaPrecioResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerListaPrecioResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ObtenerListaPrecioResult As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerListaPrecioResult As Byte)
            MyBase.New
            Me.ObtenerListaPrecioResult = ObtenerListaPrecioResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerEstadoActualRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerEstadoActual", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSLlaveCliente.ObtenerEstadoActualRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSLlaveCliente.ObtenerEstadoActualRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerEstadoActualRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Cuit As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public IDAns As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal Cuit As String, ByVal IDAns As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.Cuit = Cuit
            Me.IDAns = IDAns
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerEstadoActualResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerEstadoActualResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSLlaveCliente.ObtenerEstadoActualResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSLlaveCliente.ObtenerEstadoActualResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerEstadoActualResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ObtenerEstadoActualResult As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerEstadoActualResult As Byte)
            MyBase.New
            Me.ObtenerEstadoActualResult = ObtenerEstadoActualResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerLLaveViajanteRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerLLaveViajante", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSLlaveCliente.ObtenerLLaveViajanteRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSLlaveCliente.ObtenerLLaveViajanteRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerLLaveViajanteRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public IdViajante As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal IdViajante As String)
            MyBase.New
            Me.IdViajante = IdViajante
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerLLaveViajanteResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerLLaveViajanteResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSLlaveCliente.ObtenerLLaveViajanteResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSLlaveCliente.ObtenerLLaveViajanteResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerLLaveViajanteResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public ObtenerLLaveViajanteResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerLLaveViajanteResult As String)
            MyBase.New
            Me.ObtenerLLaveViajanteResult = ObtenerLLaveViajanteResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerLLaveCatalogoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerLLaveCatalogo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSLlaveCliente.ObtenerLLaveCatalogoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSLlaveCliente.ObtenerLLaveCatalogoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerLLaveCatalogoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Cuit As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public IDAns As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public IDViajante As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal Cuit As String, ByVal IDAns As String, ByVal IDViajante As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.Cuit = Cuit
            Me.IDAns = IDAns
            Me.IDViajante = IDViajante
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ObtenerLLaveCatalogoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ObtenerLLaveCatalogoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSLlaveCliente.ObtenerLLaveCatalogoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSLlaveCliente.ObtenerLLaveCatalogoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ObtenerLLaveCatalogoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ObtenerLLaveCatalogoResult As Byte
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ObtenerLLaveCatalogoResult As Byte)
            MyBase.New
            Me.ObtenerLLaveCatalogoResult = ObtenerLLaveCatalogoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface LLaveClienteSoapChannel
        Inherits WSLlaveCliente.LLaveClienteSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class LLaveClienteSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSLlaveCliente.LLaveClienteSoap)
        Implements WSLlaveCliente.LLaveClienteSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSLlaveCliente_LLaveClienteSoap_ObtenerListaPrecio(ByVal request As WSLlaveCliente.ObtenerListaPrecioRequest) As WSLlaveCliente.ObtenerListaPrecioResponse Implements WSLlaveCliente.LLaveClienteSoap.ObtenerListaPrecio
            Return MyBase.Channel.ObtenerListaPrecio(request)
        End Function
        
        Public Function ObtenerListaPrecio(ByVal MacAddress As String, ByVal Cuit As String, ByVal IDAns As String) As Byte
            Dim inValue As WSLlaveCliente.ObtenerListaPrecioRequest = New WSLlaveCliente.ObtenerListaPrecioRequest()
            inValue.Body = New WSLlaveCliente.ObtenerListaPrecioRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.Cuit = Cuit
            inValue.Body.IDAns = IDAns
            Dim retVal As WSLlaveCliente.ObtenerListaPrecioResponse = CType(Me,WSLlaveCliente.LLaveClienteSoap).ObtenerListaPrecio(inValue)
            Return retVal.Body.ObtenerListaPrecioResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSLlaveCliente_LLaveClienteSoap_ObtenerEstadoActual(ByVal request As WSLlaveCliente.ObtenerEstadoActualRequest) As WSLlaveCliente.ObtenerEstadoActualResponse Implements WSLlaveCliente.LLaveClienteSoap.ObtenerEstadoActual
            Return MyBase.Channel.ObtenerEstadoActual(request)
        End Function
        
        Public Function ObtenerEstadoActual(ByVal MacAddress As String, ByVal Cuit As String, ByVal IDAns As String) As Byte
            Dim inValue As WSLlaveCliente.ObtenerEstadoActualRequest = New WSLlaveCliente.ObtenerEstadoActualRequest()
            inValue.Body = New WSLlaveCliente.ObtenerEstadoActualRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.Cuit = Cuit
            inValue.Body.IDAns = IDAns
            Dim retVal As WSLlaveCliente.ObtenerEstadoActualResponse = CType(Me,WSLlaveCliente.LLaveClienteSoap).ObtenerEstadoActual(inValue)
            Return retVal.Body.ObtenerEstadoActualResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSLlaveCliente_LLaveClienteSoap_ObtenerLLaveViajante(ByVal request As WSLlaveCliente.ObtenerLLaveViajanteRequest) As WSLlaveCliente.ObtenerLLaveViajanteResponse Implements WSLlaveCliente.LLaveClienteSoap.ObtenerLLaveViajante
            Return MyBase.Channel.ObtenerLLaveViajante(request)
        End Function
        
        Public Function ObtenerLLaveViajante(ByVal IdViajante As String) As String
            Dim inValue As WSLlaveCliente.ObtenerLLaveViajanteRequest = New WSLlaveCliente.ObtenerLLaveViajanteRequest()
            inValue.Body = New WSLlaveCliente.ObtenerLLaveViajanteRequestBody()
            inValue.Body.IdViajante = IdViajante
            Dim retVal As WSLlaveCliente.ObtenerLLaveViajanteResponse = CType(Me,WSLlaveCliente.LLaveClienteSoap).ObtenerLLaveViajante(inValue)
            Return retVal.Body.ObtenerLLaveViajanteResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSLlaveCliente_LLaveClienteSoap_ObtenerLLaveCatalogo(ByVal request As WSLlaveCliente.ObtenerLLaveCatalogoRequest) As WSLlaveCliente.ObtenerLLaveCatalogoResponse Implements WSLlaveCliente.LLaveClienteSoap.ObtenerLLaveCatalogo
            Return MyBase.Channel.ObtenerLLaveCatalogo(request)
        End Function
        
        Public Function ObtenerLLaveCatalogo(ByVal MacAddress As String, ByVal Cuit As String, ByVal IDAns As String, ByVal IDViajante As String) As Byte
            Dim inValue As WSLlaveCliente.ObtenerLLaveCatalogoRequest = New WSLlaveCliente.ObtenerLLaveCatalogoRequest()
            inValue.Body = New WSLlaveCliente.ObtenerLLaveCatalogoRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.Cuit = Cuit
            inValue.Body.IDAns = IDAns
            inValue.Body.IDViajante = IDViajante
            Dim retVal As WSLlaveCliente.ObtenerLLaveCatalogoResponse = CType(Me,WSLlaveCliente.LLaveClienteSoap).ObtenerLLaveCatalogo(inValue)
            Return retVal.Body.ObtenerLLaveCatalogoResult
        End Function
    End Class
End Namespace
