'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
'
Namespace PedidosWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="PedidosSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Pedidos
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarPedido7OperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CatalogoLibraryVB.My.MySettings.Default.CatalogoLibraryVB_PedidosWS_Pedidos
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarPedido7Completed As EnviarPedido7CompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarPedido7", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarPedido7(ByVal MacAddress As String, ByVal NroPedido As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Transporte As String, ByVal Detalle As String) As Long
            Dim results() As Object = Me.Invoke("EnviarPedido7", New Object() {MacAddress, NroPedido, CodCliente, Fecha, Observaciones, Transporte, Detalle})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarPedido7Async(ByVal MacAddress As String, ByVal NroPedido As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Transporte As String, ByVal Detalle As String)
            Me.EnviarPedido7Async(MacAddress, NroPedido, CodCliente, Fecha, Observaciones, Transporte, Detalle, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarPedido7Async(ByVal MacAddress As String, ByVal NroPedido As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Transporte As String, ByVal Detalle As String, ByVal userState As Object)
            If (Me.EnviarPedido7OperationCompleted Is Nothing) Then
                Me.EnviarPedido7OperationCompleted = AddressOf Me.OnEnviarPedido7OperationCompleted
            End If
            Me.InvokeAsync("EnviarPedido7", New Object() {MacAddress, NroPedido, CodCliente, Fecha, Observaciones, Transporte, Detalle}, Me.EnviarPedido7OperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarPedido7OperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarPedido7CompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarPedido7Completed(Me, New EnviarPedido7CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub EnviarPedido7CompletedEventHandler(ByVal sender As Object, ByVal e As EnviarPedido7CompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarPedido7CompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
End Namespace
