//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Catalogo.AppConfigWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="appConfigSoap", Namespace="http://tempuri.org/")]
    public partial class appConfig : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerListaPrecioV2OperationCompleted;
        
        private System.Threading.SendOrPostCallback TenerQueEnviarInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerInfoDSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerInfoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerComandosDSOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerComandosOperationCompleted;
        
        private System.Threading.SendOrPostCallback SincronizacionAppConfigCompletadaOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public appConfig() {
            this.Url = global::Catalogo.Properties.Settings.Default.Catalogo_AppConfigWS_appConfig;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerListaPrecioV2CompletedEventHandler ObtenerListaPrecioV2Completed;
        
        /// <remarks/>
        public event TenerQueEnviarInfoCompletedEventHandler TenerQueEnviarInfoCompleted;
        
        /// <remarks/>
        public event EnviarInfoCompletedEventHandler EnviarInfoCompleted;
        
        /// <remarks/>
        public event ObtenerInfoDSCompletedEventHandler ObtenerInfoDSCompleted;
        
        /// <remarks/>
        public event ObtenerInfoCompletedEventHandler ObtenerInfoCompleted;
        
        /// <remarks/>
        public event ObtenerComandosDSCompletedEventHandler ObtenerComandosDSCompleted;
        
        /// <remarks/>
        public event ObtenerComandosCompletedEventHandler ObtenerComandosCompleted;
        
        /// <remarks/>
        public event SincronizacionAppConfigCompletadaCompletedEventHandler SincronizacionAppConfigCompletadaCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerListaPrecioV2", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public byte ObtenerListaPrecioV2(string MacAddress, string Cuit, string IDAns) {
            object[] results = this.Invoke("ObtenerListaPrecioV2", new object[] {
                        MacAddress,
                        Cuit,
                        IDAns});
            return ((byte)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerListaPrecioV2Async(string MacAddress, string Cuit, string IDAns) {
            this.ObtenerListaPrecioV2Async(MacAddress, Cuit, IDAns, null);
        }
        
        /// <remarks/>
        public void ObtenerListaPrecioV2Async(string MacAddress, string Cuit, string IDAns, object userState) {
            if ((this.ObtenerListaPrecioV2OperationCompleted == null)) {
                this.ObtenerListaPrecioV2OperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerListaPrecioV2OperationCompleted);
            }
            this.InvokeAsync("ObtenerListaPrecioV2", new object[] {
                        MacAddress,
                        Cuit,
                        IDAns}, this.ObtenerListaPrecioV2OperationCompleted, userState);
        }
        
        private void OnObtenerListaPrecioV2OperationCompleted(object arg) {
            if ((this.ObtenerListaPrecioV2Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerListaPrecioV2Completed(this, new ObtenerListaPrecioV2CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/TenerQueEnviarInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long TenerQueEnviarInfo(string MacAddress) {
            object[] results = this.Invoke("TenerQueEnviarInfo", new object[] {
                        MacAddress});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void TenerQueEnviarInfoAsync(string MacAddress) {
            this.TenerQueEnviarInfoAsync(MacAddress, null);
        }
        
        /// <remarks/>
        public void TenerQueEnviarInfoAsync(string MacAddress, object userState) {
            if ((this.TenerQueEnviarInfoOperationCompleted == null)) {
                this.TenerQueEnviarInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTenerQueEnviarInfoOperationCompleted);
            }
            this.InvokeAsync("TenerQueEnviarInfo", new object[] {
                        MacAddress}, this.TenerQueEnviarInfoOperationCompleted, userState);
        }
        
        private void OnTenerQueEnviarInfoOperationCompleted(object arg) {
            if ((this.TenerQueEnviarInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TenerQueEnviarInfoCompleted(this, new TenerQueEnviarInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long EnviarInfo(
                    string MacAddress, 
                    string Cuit, 
                    string RazonSocial, 
                    string ApellidoNombre, 
                    string Domicilio, 
                    string Telefono, 
                    string Ciudad, 
                    string Email, 
                    string IDAns, 
                    string AppCaduca, 
                    string dbCaduca, 
                    string Pin, 
                    string FechaUltimoAcceso, 
                    string Mensaje, 
                    string EnviarAuditoria, 
                    string Url, 
                    string Modem, 
                    string Version, 
                    string Build, 
                    string ListaPrecio, 
                    string Auditor) {
            object[] results = this.Invoke("EnviarInfo", new object[] {
                        MacAddress,
                        Cuit,
                        RazonSocial,
                        ApellidoNombre,
                        Domicilio,
                        Telefono,
                        Ciudad,
                        Email,
                        IDAns,
                        AppCaduca,
                        dbCaduca,
                        Pin,
                        FechaUltimoAcceso,
                        Mensaje,
                        EnviarAuditoria,
                        Url,
                        Modem,
                        Version,
                        Build,
                        ListaPrecio,
                        Auditor});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarInfoAsync(
                    string MacAddress, 
                    string Cuit, 
                    string RazonSocial, 
                    string ApellidoNombre, 
                    string Domicilio, 
                    string Telefono, 
                    string Ciudad, 
                    string Email, 
                    string IDAns, 
                    string AppCaduca, 
                    string dbCaduca, 
                    string Pin, 
                    string FechaUltimoAcceso, 
                    string Mensaje, 
                    string EnviarAuditoria, 
                    string Url, 
                    string Modem, 
                    string Version, 
                    string Build, 
                    string ListaPrecio, 
                    string Auditor) {
            this.EnviarInfoAsync(MacAddress, Cuit, RazonSocial, ApellidoNombre, Domicilio, Telefono, Ciudad, Email, IDAns, AppCaduca, dbCaduca, Pin, FechaUltimoAcceso, Mensaje, EnviarAuditoria, Url, Modem, Version, Build, ListaPrecio, Auditor, null);
        }
        
        /// <remarks/>
        public void EnviarInfoAsync(
                    string MacAddress, 
                    string Cuit, 
                    string RazonSocial, 
                    string ApellidoNombre, 
                    string Domicilio, 
                    string Telefono, 
                    string Ciudad, 
                    string Email, 
                    string IDAns, 
                    string AppCaduca, 
                    string dbCaduca, 
                    string Pin, 
                    string FechaUltimoAcceso, 
                    string Mensaje, 
                    string EnviarAuditoria, 
                    string Url, 
                    string Modem, 
                    string Version, 
                    string Build, 
                    string ListaPrecio, 
                    string Auditor, 
                    object userState) {
            if ((this.EnviarInfoOperationCompleted == null)) {
                this.EnviarInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarInfoOperationCompleted);
            }
            this.InvokeAsync("EnviarInfo", new object[] {
                        MacAddress,
                        Cuit,
                        RazonSocial,
                        ApellidoNombre,
                        Domicilio,
                        Telefono,
                        Ciudad,
                        Email,
                        IDAns,
                        AppCaduca,
                        dbCaduca,
                        Pin,
                        FechaUltimoAcceso,
                        Mensaje,
                        EnviarAuditoria,
                        Url,
                        Modem,
                        Version,
                        Build,
                        ListaPrecio,
                        Auditor}, this.EnviarInfoOperationCompleted, userState);
        }
        
        private void OnEnviarInfoOperationCompleted(object arg) {
            if ((this.EnviarInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarInfoCompleted(this, new EnviarInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerInfoDS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerInfoDS(string MacAddress) {
            object[] results = this.Invoke("ObtenerInfoDS", new object[] {
                        MacAddress});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerInfoDSAsync(string MacAddress) {
            this.ObtenerInfoDSAsync(MacAddress, null);
        }
        
        /// <remarks/>
        public void ObtenerInfoDSAsync(string MacAddress, object userState) {
            if ((this.ObtenerInfoDSOperationCompleted == null)) {
                this.ObtenerInfoDSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerInfoDSOperationCompleted);
            }
            this.InvokeAsync("ObtenerInfoDS", new object[] {
                        MacAddress}, this.ObtenerInfoDSOperationCompleted, userState);
        }
        
        private void OnObtenerInfoDSOperationCompleted(object arg) {
            if ((this.ObtenerInfoDSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerInfoDSCompleted(this, new ObtenerInfoDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerInfo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerInfo(string MacAddress) {
            object[] results = this.Invoke("ObtenerInfo", new object[] {
                        MacAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerInfoAsync(string MacAddress) {
            this.ObtenerInfoAsync(MacAddress, null);
        }
        
        /// <remarks/>
        public void ObtenerInfoAsync(string MacAddress, object userState) {
            if ((this.ObtenerInfoOperationCompleted == null)) {
                this.ObtenerInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerInfoOperationCompleted);
            }
            this.InvokeAsync("ObtenerInfo", new object[] {
                        MacAddress}, this.ObtenerInfoOperationCompleted, userState);
        }
        
        private void OnObtenerInfoOperationCompleted(object arg) {
            if ((this.ObtenerInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerInfoCompleted(this, new ObtenerInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerComandosDS", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet ObtenerComandosDS(string MacAddress) {
            object[] results = this.Invoke("ObtenerComandosDS", new object[] {
                        MacAddress});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerComandosDSAsync(string MacAddress) {
            this.ObtenerComandosDSAsync(MacAddress, null);
        }
        
        /// <remarks/>
        public void ObtenerComandosDSAsync(string MacAddress, object userState) {
            if ((this.ObtenerComandosDSOperationCompleted == null)) {
                this.ObtenerComandosDSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerComandosDSOperationCompleted);
            }
            this.InvokeAsync("ObtenerComandosDS", new object[] {
                        MacAddress}, this.ObtenerComandosDSOperationCompleted, userState);
        }
        
        private void OnObtenerComandosDSOperationCompleted(object arg) {
            if ((this.ObtenerComandosDSCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerComandosDSCompleted(this, new ObtenerComandosDSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerComandos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerComandos(string MacAddress) {
            object[] results = this.Invoke("ObtenerComandos", new object[] {
                        MacAddress});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerComandosAsync(string MacAddress) {
            this.ObtenerComandosAsync(MacAddress, null);
        }
        
        /// <remarks/>
        public void ObtenerComandosAsync(string MacAddress, object userState) {
            if ((this.ObtenerComandosOperationCompleted == null)) {
                this.ObtenerComandosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerComandosOperationCompleted);
            }
            this.InvokeAsync("ObtenerComandos", new object[] {
                        MacAddress}, this.ObtenerComandosOperationCompleted, userState);
        }
        
        private void OnObtenerComandosOperationCompleted(object arg) {
            if ((this.ObtenerComandosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerComandosCompleted(this, new ObtenerComandosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SincronizacionAppConfigCompletada", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void SincronizacionAppConfigCompletada(string MacAddress) {
            this.Invoke("SincronizacionAppConfigCompletada", new object[] {
                        MacAddress});
        }
        
        /// <remarks/>
        public void SincronizacionAppConfigCompletadaAsync(string MacAddress) {
            this.SincronizacionAppConfigCompletadaAsync(MacAddress, null);
        }
        
        /// <remarks/>
        public void SincronizacionAppConfigCompletadaAsync(string MacAddress, object userState) {
            if ((this.SincronizacionAppConfigCompletadaOperationCompleted == null)) {
                this.SincronizacionAppConfigCompletadaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSincronizacionAppConfigCompletadaOperationCompleted);
            }
            this.InvokeAsync("SincronizacionAppConfigCompletada", new object[] {
                        MacAddress}, this.SincronizacionAppConfigCompletadaOperationCompleted, userState);
        }
        
        private void OnSincronizacionAppConfigCompletadaOperationCompleted(object arg) {
            if ((this.SincronizacionAppConfigCompletadaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SincronizacionAppConfigCompletadaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerListaPrecioV2CompletedEventHandler(object sender, ObtenerListaPrecioV2CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerListaPrecioV2CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerListaPrecioV2CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void TenerQueEnviarInfoCompletedEventHandler(object sender, TenerQueEnviarInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TenerQueEnviarInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TenerQueEnviarInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EnviarInfoCompletedEventHandler(object sender, EnviarInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerInfoDSCompletedEventHandler(object sender, ObtenerInfoDSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerInfoDSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerInfoDSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerInfoCompletedEventHandler(object sender, ObtenerInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerComandosDSCompletedEventHandler(object sender, ObtenerComandosDSCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerComandosDSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerComandosDSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerComandosCompletedEventHandler(object sender, ObtenerComandosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerComandosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerComandosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void SincronizacionAppConfigCompletadaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591