'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSRecibos
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSRecibos.Recibos_v_303Soap")>  _
    Public Interface Recibos_v_303Soap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EnviarRecibo", ReplyAction:="*")>  _
        Function EnviarRecibo(ByVal request As WSRecibos.EnviarReciboRequest) As WSRecibos.EnviarReciboResponse
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EnviarRecibo317", ReplyAction:="*")>  _
        Function EnviarRecibo317(ByVal request As WSRecibos.EnviarRecibo317Request) As WSRecibos.EnviarRecibo317Response
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarReciboRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarRecibo", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRecibos.EnviarReciboRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRecibos.EnviarReciboRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarReciboRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NroRecibo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public CodCliente As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Fecha As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Bahia As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Total As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Detalle As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Facturas As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.NroRecibo = NroRecibo
            Me.CodCliente = CodCliente
            Me.Fecha = Fecha
            Me.Bahia = Bahia
            Me.Total = Total
            Me.Detalle = Detalle
            Me.Facturas = Facturas
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarReciboResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarReciboResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRecibos.EnviarReciboResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRecibos.EnviarReciboResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarReciboResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public EnviarReciboResult As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EnviarReciboResult As Long)
            MyBase.New
            Me.EnviarReciboResult = EnviarReciboResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarRecibo317Request
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarRecibo317", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRecibos.EnviarRecibo317RequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRecibos.EnviarRecibo317RequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarRecibo317RequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NroRecibo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public CodCliente As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Fecha As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Bahia As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Total As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Detalle As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Facturas As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public NotasCredito As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String, ByVal NotasCredito As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.NroRecibo = NroRecibo
            Me.CodCliente = CodCliente
            Me.Fecha = Fecha
            Me.Bahia = Bahia
            Me.Total = Total
            Me.Detalle = Detalle
            Me.Facturas = Facturas
            Me.NotasCredito = NotasCredito
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarRecibo317Response
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarRecibo317Response", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSRecibos.EnviarRecibo317ResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSRecibos.EnviarRecibo317ResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarRecibo317ResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public EnviarRecibo317Result As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EnviarRecibo317Result As Long)
            MyBase.New
            Me.EnviarRecibo317Result = EnviarRecibo317Result
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface Recibos_v_303SoapChannel
        Inherits WSRecibos.Recibos_v_303Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class Recibos_v_303SoapClient
        Inherits System.ServiceModel.ClientBase(Of WSRecibos.Recibos_v_303Soap)
        Implements WSRecibos.Recibos_v_303Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRecibos_Recibos_v_303Soap_EnviarRecibo(ByVal request As WSRecibos.EnviarReciboRequest) As WSRecibos.EnviarReciboResponse Implements WSRecibos.Recibos_v_303Soap.EnviarRecibo
            Return MyBase.Channel.EnviarRecibo(request)
        End Function
        
        Public Function EnviarRecibo(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String) As Long
            Dim inValue As WSRecibos.EnviarReciboRequest = New WSRecibos.EnviarReciboRequest()
            inValue.Body = New WSRecibos.EnviarReciboRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.NroRecibo = NroRecibo
            inValue.Body.CodCliente = CodCliente
            inValue.Body.Fecha = Fecha
            inValue.Body.Bahia = Bahia
            inValue.Body.Total = Total
            inValue.Body.Detalle = Detalle
            inValue.Body.Facturas = Facturas
            Dim retVal As WSRecibos.EnviarReciboResponse = CType(Me,WSRecibos.Recibos_v_303Soap).EnviarRecibo(inValue)
            Return retVal.Body.EnviarReciboResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSRecibos_Recibos_v_303Soap_EnviarRecibo317(ByVal request As WSRecibos.EnviarRecibo317Request) As WSRecibos.EnviarRecibo317Response Implements WSRecibos.Recibos_v_303Soap.EnviarRecibo317
            Return MyBase.Channel.EnviarRecibo317(request)
        End Function
        
        Public Function EnviarRecibo317(ByVal MacAddress As String, ByVal NroRecibo As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Bahia As String, ByVal Total As String, ByVal Detalle As String, ByVal Facturas As String, ByVal NotasCredito As String) As Long
            Dim inValue As WSRecibos.EnviarRecibo317Request = New WSRecibos.EnviarRecibo317Request()
            inValue.Body = New WSRecibos.EnviarRecibo317RequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.NroRecibo = NroRecibo
            inValue.Body.CodCliente = CodCliente
            inValue.Body.Fecha = Fecha
            inValue.Body.Bahia = Bahia
            inValue.Body.Total = Total
            inValue.Body.Detalle = Detalle
            inValue.Body.Facturas = Facturas
            inValue.Body.NotasCredito = NotasCredito
            Dim retVal As WSRecibos.EnviarRecibo317Response = CType(Me,WSRecibos.Recibos_v_303Soap).EnviarRecibo317(inValue)
            Return retVal.Body.EnviarRecibo317Result
        End Function
    End Class
End Namespace
