'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSInterDeposito
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSInterDeposito.InterDepositoSoap")>  _
    Public Interface InterDepositoSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EnviarInterDeposito", ReplyAction:="*")>  _
        Function EnviarInterDeposito(ByVal request As WSInterDeposito.EnviarInterDepositoRequest) As WSInterDeposito.EnviarInterDepositoResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarInterDepositoRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarInterDeposito", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSInterDeposito.EnviarInterDepositoRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSInterDeposito.EnviarInterDepositoRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarInterDepositoRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NroInterDeposito As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public CodCliente As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Bco_Dep_Tipo As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Bco_Dep_Fecha As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Bco_Dep_Numero As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=6)>  _
        Public Bco_Dep_Monto As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=7)>  _
        Public Bco_Dep_Ch_Cantidad As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=8)>  _
        Public Bco_Dep_IdCta As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=9)>  _
        Public Observaciones As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=10)>  _
        Public Detalle As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal NroInterDeposito As String, ByVal CodCliente As String, ByVal Bco_Dep_Tipo As String, ByVal Bco_Dep_Fecha As String, ByVal Bco_Dep_Numero As String, ByVal Bco_Dep_Monto As String, ByVal Bco_Dep_Ch_Cantidad As String, ByVal Bco_Dep_IdCta As String, ByVal Observaciones As String, ByVal Detalle As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.NroInterDeposito = NroInterDeposito
            Me.CodCliente = CodCliente
            Me.Bco_Dep_Tipo = Bco_Dep_Tipo
            Me.Bco_Dep_Fecha = Bco_Dep_Fecha
            Me.Bco_Dep_Numero = Bco_Dep_Numero
            Me.Bco_Dep_Monto = Bco_Dep_Monto
            Me.Bco_Dep_Ch_Cantidad = Bco_Dep_Ch_Cantidad
            Me.Bco_Dep_IdCta = Bco_Dep_IdCta
            Me.Observaciones = Observaciones
            Me.Detalle = Detalle
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarInterDepositoResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarInterDepositoResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSInterDeposito.EnviarInterDepositoResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSInterDeposito.EnviarInterDepositoResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarInterDepositoResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public EnviarInterDepositoResult As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EnviarInterDepositoResult As Long)
            MyBase.New
            Me.EnviarInterDepositoResult = EnviarInterDepositoResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface InterDepositoSoapChannel
        Inherits WSInterDeposito.InterDepositoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class InterDepositoSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSInterDeposito.InterDepositoSoap)
        Implements WSInterDeposito.InterDepositoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSInterDeposito_InterDepositoSoap_EnviarInterDeposito(ByVal request As WSInterDeposito.EnviarInterDepositoRequest) As WSInterDeposito.EnviarInterDepositoResponse Implements WSInterDeposito.InterDepositoSoap.EnviarInterDeposito
            Return MyBase.Channel.EnviarInterDeposito(request)
        End Function
        
        Public Function EnviarInterDeposito(ByVal MacAddress As String, ByVal NroInterDeposito As String, ByVal CodCliente As String, ByVal Bco_Dep_Tipo As String, ByVal Bco_Dep_Fecha As String, ByVal Bco_Dep_Numero As String, ByVal Bco_Dep_Monto As String, ByVal Bco_Dep_Ch_Cantidad As String, ByVal Bco_Dep_IdCta As String, ByVal Observaciones As String, ByVal Detalle As String) As Long
            Dim inValue As WSInterDeposito.EnviarInterDepositoRequest = New WSInterDeposito.EnviarInterDepositoRequest()
            inValue.Body = New WSInterDeposito.EnviarInterDepositoRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.NroInterDeposito = NroInterDeposito
            inValue.Body.CodCliente = CodCliente
            inValue.Body.Bco_Dep_Tipo = Bco_Dep_Tipo
            inValue.Body.Bco_Dep_Fecha = Bco_Dep_Fecha
            inValue.Body.Bco_Dep_Numero = Bco_Dep_Numero
            inValue.Body.Bco_Dep_Monto = Bco_Dep_Monto
            inValue.Body.Bco_Dep_Ch_Cantidad = Bco_Dep_Ch_Cantidad
            inValue.Body.Bco_Dep_IdCta = Bco_Dep_IdCta
            inValue.Body.Observaciones = Observaciones
            inValue.Body.Detalle = Detalle
            Dim retVal As WSInterDeposito.EnviarInterDepositoResponse = CType(Me,WSInterDeposito.InterDepositoSoap).EnviarInterDeposito(inValue)
            Return retVal.Body.EnviarInterDepositoResult
        End Function
    End Class
End Namespace
