//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Catalogo.VerEstadoPedidoWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VerEstadoPedidoSoap", Namespace="http://tempuri.org/")]
    public partial class VerEstadoPedido : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerEstadoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerZonaClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VerEstadoPedido() {
            this.Url = global::Catalogo.Properties.Settings.Default.Catalogo_VerEstadoPedidoWS_VerEstadoPedido;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerEstadoCompletedEventHandler ObtenerEstadoCompleted;
        
        /// <remarks/>
        public event ObtenerZonaClienteCompletedEventHandler ObtenerZonaClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerEstado", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerEstado(string MacAddress, string IDAns, string PedidoNro) {
            object[] results = this.Invoke("ObtenerEstado", new object[] {
                        MacAddress,
                        IDAns,
                        PedidoNro});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        internal void ObtenerEstadoAsync(string MacAddress, string IDAns, string PedidoNro) {
            this.ObtenerEstadoAsync(MacAddress, IDAns, PedidoNro, null);
        }
        
        /// <remarks/>
        internal void ObtenerEstadoAsync(string MacAddress, string IDAns, string PedidoNro, object userState) {
            if ((this.ObtenerEstadoOperationCompleted == null)) {
                this.ObtenerEstadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerEstadoOperationCompleted);
            }
            this.InvokeAsync("ObtenerEstado", new object[] {
                        MacAddress,
                        IDAns,
                        PedidoNro}, this.ObtenerEstadoOperationCompleted, userState);
        }
        
        private void OnObtenerEstadoOperationCompleted(object arg) {
            if ((this.ObtenerEstadoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerEstadoCompleted(this, new ObtenerEstadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerZonaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerZonaCliente(string MacAddress, string IDAns) {
            object[] results = this.Invoke("ObtenerZonaCliente", new object[] {
                        MacAddress,
                        IDAns});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        internal void ObtenerZonaClienteAsync(string MacAddress, string IDAns) {
            this.ObtenerZonaClienteAsync(MacAddress, IDAns, null);
        }
        
        /// <remarks/>
        internal void ObtenerZonaClienteAsync(string MacAddress, string IDAns, object userState) {
            if ((this.ObtenerZonaClienteOperationCompleted == null)) {
                this.ObtenerZonaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerZonaClienteOperationCompleted);
            }
            this.InvokeAsync("ObtenerZonaCliente", new object[] {
                        MacAddress,
                        IDAns}, this.ObtenerZonaClienteOperationCompleted, userState);
        }
        
        private void OnObtenerZonaClienteOperationCompleted(object arg) {
            if ((this.ObtenerZonaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerZonaClienteCompleted(this, new ObtenerZonaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerEstadoCompletedEventHandler(object sender, ObtenerEstadoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerEstadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerEstadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerZonaClienteCompletedEventHandler(object sender, ObtenerZonaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerZonaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerZonaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591