//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Catalogo.UpdateNovedadesCatalogoWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="CatalogoNovedadesSoap", Namespace="http://tempuri.org/")]
    public partial class CatalogoNovedades : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetTodasLasNovedades_CantidadOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTodasLasNovedades_Datos_RegistrosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public CatalogoNovedades() {
            this.Url = global::Catalogo.Properties.Settings.Default.Catalogo_UpdateNovedadesCatalogoWS_CatalogoNovedades;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetTodasLasNovedades_CantidadCompletedEventHandler GetTodasLasNovedades_CantidadCompleted;
        
        /// <remarks/>
        public event GetTodasLasNovedades_Datos_RegistrosCompletedEventHandler GetTodasLasNovedades_Datos_RegistrosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTodasLasNovedades_Cantidad", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long GetTodasLasNovedades_Cantidad(string MacAddress, int IdNovedad) {
            object[] results = this.Invoke("GetTodasLasNovedades_Cantidad", new object[] {
                        MacAddress,
                        IdNovedad});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        internal void GetTodasLasNovedades_CantidadAsync(string MacAddress, int IdNovedad) {
            this.GetTodasLasNovedades_CantidadAsync(MacAddress, IdNovedad, null);
        }
        
        /// <remarks/>
        internal void GetTodasLasNovedades_CantidadAsync(string MacAddress, int IdNovedad, object userState) {
            if ((this.GetTodasLasNovedades_CantidadOperationCompleted == null)) {
                this.GetTodasLasNovedades_CantidadOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTodasLasNovedades_CantidadOperationCompleted);
            }
            this.InvokeAsync("GetTodasLasNovedades_Cantidad", new object[] {
                        MacAddress,
                        IdNovedad}, this.GetTodasLasNovedades_CantidadOperationCompleted, userState);
        }
        
        private void OnGetTodasLasNovedades_CantidadOperationCompleted(object arg) {
            if ((this.GetTodasLasNovedades_CantidadCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTodasLasNovedades_CantidadCompleted(this, new GetTodasLasNovedades_CantidadCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetTodasLasNovedades_Datos_Registros", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataSet GetTodasLasNovedades_Datos_Registros(string MacAddress, long LastID) {
            object[] results = this.Invoke("GetTodasLasNovedades_Datos_Registros", new object[] {
                        MacAddress,
                        LastID});
            return ((System.Data.DataSet)(results[0]));
        }
        
        /// <remarks/>
        internal void GetTodasLasNovedades_Datos_RegistrosAsync(string MacAddress, long LastID) {
            this.GetTodasLasNovedades_Datos_RegistrosAsync(MacAddress, LastID, null);
        }
        
        /// <remarks/>
        internal void GetTodasLasNovedades_Datos_RegistrosAsync(string MacAddress, long LastID, object userState) {
            if ((this.GetTodasLasNovedades_Datos_RegistrosOperationCompleted == null)) {
                this.GetTodasLasNovedades_Datos_RegistrosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTodasLasNovedades_Datos_RegistrosOperationCompleted);
            }
            this.InvokeAsync("GetTodasLasNovedades_Datos_Registros", new object[] {
                        MacAddress,
                        LastID}, this.GetTodasLasNovedades_Datos_RegistrosOperationCompleted, userState);
        }
        
        private void OnGetTodasLasNovedades_Datos_RegistrosOperationCompleted(object arg) {
            if ((this.GetTodasLasNovedades_Datos_RegistrosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTodasLasNovedades_Datos_RegistrosCompleted(this, new GetTodasLasNovedades_Datos_RegistrosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTodasLasNovedades_CantidadCompletedEventHandler(object sender, GetTodasLasNovedades_CantidadCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTodasLasNovedades_CantidadCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTodasLasNovedades_CantidadCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void GetTodasLasNovedades_Datos_RegistrosCompletedEventHandler(object sender, GetTodasLasNovedades_Datos_RegistrosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTodasLasNovedades_Datos_RegistrosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTodasLasNovedades_Datos_RegistrosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataSet Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataSet)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591