'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSClientesNovedades
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSClientesNovedades.ClientesNovedadesSoap")>  _
    Public Interface ClientesNovedadesSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/ClientesNovedades", ReplyAction:="*")>  _
        Function ClientesNovedades(ByVal request As WSClientesNovedades.ClientesNovedadesRequest) As WSClientesNovedades.ClientesNovedadesResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ClientesNovedadesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ClientesNovedades", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSClientesNovedades.ClientesNovedadesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSClientesNovedades.ClientesNovedadesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClientesNovedadesRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Fechas As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Novedades As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Clientes As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal Fechas As String, ByVal Novedades As String, ByVal Clientes As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.Fechas = Fechas
            Me.Novedades = Novedades
            Me.Clientes = Clientes
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class ClientesNovedadesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="ClientesNovedadesResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSClientesNovedades.ClientesNovedadesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSClientesNovedades.ClientesNovedadesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class ClientesNovedadesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public ClientesNovedadesResult As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal ClientesNovedadesResult As Long)
            MyBase.New
            Me.ClientesNovedadesResult = ClientesNovedadesResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ClientesNovedadesSoapChannel
        Inherits WSClientesNovedades.ClientesNovedadesSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ClientesNovedadesSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSClientesNovedades.ClientesNovedadesSoap)
        Implements WSClientesNovedades.ClientesNovedadesSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSClientesNovedades_ClientesNovedadesSoap_ClientesNovedades(ByVal request As WSClientesNovedades.ClientesNovedadesRequest) As WSClientesNovedades.ClientesNovedadesResponse Implements WSClientesNovedades.ClientesNovedadesSoap.ClientesNovedades
            Return MyBase.Channel.ClientesNovedades(request)
        End Function
        
        Public Function ClientesNovedades(ByVal MacAddress As String, ByVal Fechas As String, ByVal Novedades As String, ByVal Clientes As String) As Long
            Dim inValue As WSClientesNovedades.ClientesNovedadesRequest = New WSClientesNovedades.ClientesNovedadesRequest()
            inValue.Body = New WSClientesNovedades.ClientesNovedadesRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.Fechas = Fechas
            inValue.Body.Novedades = Novedades
            inValue.Body.Clientes = Clientes
            Dim retVal As WSClientesNovedades.ClientesNovedadesResponse = CType(Me,WSClientesNovedades.ClientesNovedadesSoap).ClientesNovedades(inValue)
            Return retVal.Body.ClientesNovedadesResult
        End Function
    End Class
End Namespace
