'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSAudit
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSAudit.audit_v_304Soap")>  _
    Public Interface audit_v_304Soap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/AuditInBlock304", ReplyAction:="*")>  _
        Function AuditInBlock304(ByVal request As WSAudit.AuditInBlock304Request) As WSAudit.AuditInBlock304Response
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AuditInBlock304Request
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AuditInBlock304", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSAudit.AuditInBlock304RequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSAudit.AuditInBlock304RequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AuditInBlock304RequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public Fechas As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public Descripciones As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public IDs As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal Fechas As String, ByVal Descripciones As String, ByVal IDs As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.Fechas = Fechas
            Me.Descripciones = Descripciones
            Me.IDs = IDs
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class AuditInBlock304Response
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="AuditInBlock304Response", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSAudit.AuditInBlock304ResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSAudit.AuditInBlock304ResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class AuditInBlock304ResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public AuditInBlock304Result As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal AuditInBlock304Result As Long)
            MyBase.New
            Me.AuditInBlock304Result = AuditInBlock304Result
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface audit_v_304SoapChannel
        Inherits WSAudit.audit_v_304Soap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class audit_v_304SoapClient
        Inherits System.ServiceModel.ClientBase(Of WSAudit.audit_v_304Soap)
        Implements WSAudit.audit_v_304Soap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSAudit_audit_v_304Soap_AuditInBlock304(ByVal request As WSAudit.AuditInBlock304Request) As WSAudit.AuditInBlock304Response Implements WSAudit.audit_v_304Soap.AuditInBlock304
            Return MyBase.Channel.AuditInBlock304(request)
        End Function
        
        Public Function AuditInBlock304(ByVal MacAddress As String, ByVal Fechas As String, ByVal Descripciones As String, ByVal IDs As String) As Long
            Dim inValue As WSAudit.AuditInBlock304Request = New WSAudit.AuditInBlock304Request()
            inValue.Body = New WSAudit.AuditInBlock304RequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.Fechas = Fechas
            inValue.Body.Descripciones = Descripciones
            inValue.Body.IDs = IDs
            Dim retVal As WSAudit.AuditInBlock304Response = CType(Me,WSAudit.audit_v_304Soap).AuditInBlock304(inValue)
            Return retVal.Body.AuditInBlock304Result
        End Function
    End Class
End Namespace
