'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.17929
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.17929.
'
Namespace DevolucionWS
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="DevolucionSoap", [Namespace]:="http://tempuri.org/")>  _
    Partial Public Class Devolucion
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        Private EnviarDevolucionOperationCompleted As System.Threading.SendOrPostCallback
        
        Private useDefaultCredentialsSetExplicitly As Boolean
        
        '''<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = Global.CatalogoLibraryVB.My.MySettings.Default.CatalogoLibraryVB_DevolucionWS_Devolucion
            If (Me.IsLocalFileSystemWebService(Me.Url) = true) Then
                Me.UseDefaultCredentials = true
                Me.useDefaultCredentialsSetExplicitly = false
            Else
                Me.useDefaultCredentialsSetExplicitly = true
            End If
        End Sub
        
        Public Shadows Property Url() As String
            Get
                Return MyBase.Url
            End Get
            Set
                If (((Me.IsLocalFileSystemWebService(MyBase.Url) = true)  _
                            AndAlso (Me.useDefaultCredentialsSetExplicitly = false))  _
                            AndAlso (Me.IsLocalFileSystemWebService(value) = false)) Then
                    MyBase.UseDefaultCredentials = false
                End If
                MyBase.Url = value
            End Set
        End Property
        
        Public Shadows Property UseDefaultCredentials() As Boolean
            Get
                Return MyBase.UseDefaultCredentials
            End Get
            Set
                MyBase.UseDefaultCredentials = value
                Me.useDefaultCredentialsSetExplicitly = true
            End Set
        End Property
        
        '''<remarks/>
        Public Event EnviarDevolucionCompleted As EnviarDevolucionCompletedEventHandler
        
        '''<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarDevolucion", RequestNamespace:="http://tempuri.org/", ResponseNamespace:="http://tempuri.org/", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function EnviarDevolucion(ByVal MacAddress As String, ByVal NroDevolucion As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Detalle As String) As Long
            Dim results() As Object = Me.Invoke("EnviarDevolucion", New Object() {MacAddress, NroDevolucion, CodCliente, Fecha, Observaciones, Detalle})
            Return CType(results(0),Long)
        End Function
        
        '''<remarks/>
        Public Overloads Sub EnviarDevolucionAsync(ByVal MacAddress As String, ByVal NroDevolucion As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Detalle As String)
            Me.EnviarDevolucionAsync(MacAddress, NroDevolucion, CodCliente, Fecha, Observaciones, Detalle, Nothing)
        End Sub
        
        '''<remarks/>
        Public Overloads Sub EnviarDevolucionAsync(ByVal MacAddress As String, ByVal NroDevolucion As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Detalle As String, ByVal userState As Object)
            If (Me.EnviarDevolucionOperationCompleted Is Nothing) Then
                Me.EnviarDevolucionOperationCompleted = AddressOf Me.OnEnviarDevolucionOperationCompleted
            End If
            Me.InvokeAsync("EnviarDevolucion", New Object() {MacAddress, NroDevolucion, CodCliente, Fecha, Observaciones, Detalle}, Me.EnviarDevolucionOperationCompleted, userState)
        End Sub
        
        Private Sub OnEnviarDevolucionOperationCompleted(ByVal arg As Object)
            If (Not (Me.EnviarDevolucionCompletedEvent) Is Nothing) Then
                Dim invokeArgs As System.Web.Services.Protocols.InvokeCompletedEventArgs = CType(arg,System.Web.Services.Protocols.InvokeCompletedEventArgs)
                RaiseEvent EnviarDevolucionCompleted(Me, New EnviarDevolucionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState))
            End If
        End Sub
        
        '''<remarks/>
        Public Shadows Sub CancelAsync(ByVal userState As Object)
            MyBase.CancelAsync(userState)
        End Sub
        
        Private Function IsLocalFileSystemWebService(ByVal url As String) As Boolean
            If ((url Is Nothing)  _
                        OrElse (url Is String.Empty)) Then
                Return false
            End If
            Dim wsUri As System.Uri = New System.Uri(url)
            If ((wsUri.Port >= 1024)  _
                        AndAlso (String.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) = 0)) Then
                Return true
            End If
            Return false
        End Function
    End Class
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")>  _
    Public Delegate Sub EnviarDevolucionCompletedEventHandler(ByVal sender As Object, ByVal e As EnviarDevolucionCompletedEventArgs)
    
    '''<remarks/>
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929"),  _
     System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code")>  _
    Partial Public Class EnviarDevolucionCompletedEventArgs
        Inherits System.ComponentModel.AsyncCompletedEventArgs
        
        Private results() As Object
        
        Friend Sub New(ByVal results() As Object, ByVal exception As System.Exception, ByVal cancelled As Boolean, ByVal userState As Object)
            MyBase.New(exception, cancelled, userState)
            Me.results = results
        End Sub
        
        '''<remarks/>
        Public ReadOnly Property Result() As Long
            Get
                Me.RaiseExceptionIfNecessary
                Return CType(Me.results(0),Long)
            End Get
        End Property
    End Class
End Namespace
