//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Catalogo.RecibosWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Recibos_v_303Soap", Namespace="http://tempuri.org/")]
    public partial class Recibos_v_303 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback EnviarReciboOperationCompleted;
        
        private System.Threading.SendOrPostCallback EnviarRecibo317OperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Recibos_v_303() {
            this.Url = global::Catalogo.Properties.Settings.Default.Catalogo_RecibosWS_Recibos_v_303;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event EnviarReciboCompletedEventHandler EnviarReciboCompleted;
        
        /// <remarks/>
        public event EnviarRecibo317CompletedEventHandler EnviarRecibo317Completed;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarRecibo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long EnviarRecibo(string MacAddress, string NroRecibo, string CodCliente, string Fecha, string Bahia, string Total, string Detalle, string Facturas) {
            object[] results = this.Invoke("EnviarRecibo", new object[] {
                        MacAddress,
                        NroRecibo,
                        CodCliente,
                        Fecha,
                        Bahia,
                        Total,
                        Detalle,
                        Facturas});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarReciboAsync(string MacAddress, string NroRecibo, string CodCliente, string Fecha, string Bahia, string Total, string Detalle, string Facturas) {
            this.EnviarReciboAsync(MacAddress, NroRecibo, CodCliente, Fecha, Bahia, Total, Detalle, Facturas, null);
        }
        
        /// <remarks/>
        public void EnviarReciboAsync(string MacAddress, string NroRecibo, string CodCliente, string Fecha, string Bahia, string Total, string Detalle, string Facturas, object userState) {
            if ((this.EnviarReciboOperationCompleted == null)) {
                this.EnviarReciboOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarReciboOperationCompleted);
            }
            this.InvokeAsync("EnviarRecibo", new object[] {
                        MacAddress,
                        NroRecibo,
                        CodCliente,
                        Fecha,
                        Bahia,
                        Total,
                        Detalle,
                        Facturas}, this.EnviarReciboOperationCompleted, userState);
        }
        
        private void OnEnviarReciboOperationCompleted(object arg) {
            if ((this.EnviarReciboCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarReciboCompleted(this, new EnviarReciboCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/EnviarRecibo317", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public long EnviarRecibo317(string MacAddress, string NroRecibo, string CodCliente, string Fecha, string Bahia, string Total, string Detalle, string Facturas, string NotasCredito) {
            object[] results = this.Invoke("EnviarRecibo317", new object[] {
                        MacAddress,
                        NroRecibo,
                        CodCliente,
                        Fecha,
                        Bahia,
                        Total,
                        Detalle,
                        Facturas,
                        NotasCredito});
            return ((long)(results[0]));
        }
        
        /// <remarks/>
        public void EnviarRecibo317Async(string MacAddress, string NroRecibo, string CodCliente, string Fecha, string Bahia, string Total, string Detalle, string Facturas, string NotasCredito) {
            this.EnviarRecibo317Async(MacAddress, NroRecibo, CodCliente, Fecha, Bahia, Total, Detalle, Facturas, NotasCredito, null);
        }
        
        /// <remarks/>
        public void EnviarRecibo317Async(string MacAddress, string NroRecibo, string CodCliente, string Fecha, string Bahia, string Total, string Detalle, string Facturas, string NotasCredito, object userState) {
            if ((this.EnviarRecibo317OperationCompleted == null)) {
                this.EnviarRecibo317OperationCompleted = new System.Threading.SendOrPostCallback(this.OnEnviarRecibo317OperationCompleted);
            }
            this.InvokeAsync("EnviarRecibo317", new object[] {
                        MacAddress,
                        NroRecibo,
                        CodCliente,
                        Fecha,
                        Bahia,
                        Total,
                        Detalle,
                        Facturas,
                        NotasCredito}, this.EnviarRecibo317OperationCompleted, userState);
        }
        
        private void OnEnviarRecibo317OperationCompleted(object arg) {
            if ((this.EnviarRecibo317Completed != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EnviarRecibo317Completed(this, new EnviarRecibo317CompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EnviarReciboCompletedEventHandler(object sender, EnviarReciboCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarReciboCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarReciboCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void EnviarRecibo317CompletedEventHandler(object sender, EnviarRecibo317CompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EnviarRecibo317CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EnviarRecibo317CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public long Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((long)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591