//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Catalogo.VerExistenciaWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="VerExistenciaSoap", Namespace="http://tempuri.org/")]
    public partial class VerExistencia : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerExistenciaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerZonaClienteOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public VerExistencia() {
            this.Url = global::Catalogo.Properties.Settings.Default.Catalogo_VerExistenciaWS_VerExistencia;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerExistenciaCompletedEventHandler ObtenerExistenciaCompleted;
        
        /// <remarks/>
        public event ObtenerZonaClienteCompletedEventHandler ObtenerZonaClienteCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerExistencia", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerExistencia(string MacAddress, string IDAns, string IdProducto) {
            object[] results = this.Invoke("ObtenerExistencia", new object[] {
                        MacAddress,
                        IDAns,
                        IdProducto});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerExistenciaAsync(string MacAddress, string IDAns, string IdProducto) {
            this.ObtenerExistenciaAsync(MacAddress, IDAns, IdProducto, null);
        }
        
        /// <remarks/>
        public void ObtenerExistenciaAsync(string MacAddress, string IDAns, string IdProducto, object userState) {
            if ((this.ObtenerExistenciaOperationCompleted == null)) {
                this.ObtenerExistenciaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerExistenciaOperationCompleted);
            }
            this.InvokeAsync("ObtenerExistencia", new object[] {
                        MacAddress,
                        IDAns,
                        IdProducto}, this.ObtenerExistenciaOperationCompleted, userState);
        }
        
        private void OnObtenerExistenciaOperationCompleted(object arg) {
            if ((this.ObtenerExistenciaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerExistenciaCompleted(this, new ObtenerExistenciaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerZonaCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerZonaCliente(string MacAddress, string IDAns) {
            object[] results = this.Invoke("ObtenerZonaCliente", new object[] {
                        MacAddress,
                        IDAns});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ObtenerZonaClienteAsync(string MacAddress, string IDAns) {
            this.ObtenerZonaClienteAsync(MacAddress, IDAns, null);
        }
        
        /// <remarks/>
        public void ObtenerZonaClienteAsync(string MacAddress, string IDAns, object userState) {
            if ((this.ObtenerZonaClienteOperationCompleted == null)) {
                this.ObtenerZonaClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerZonaClienteOperationCompleted);
            }
            this.InvokeAsync("ObtenerZonaCliente", new object[] {
                        MacAddress,
                        IDAns}, this.ObtenerZonaClienteOperationCompleted, userState);
        }
        
        private void OnObtenerZonaClienteOperationCompleted(object arg) {
            if ((this.ObtenerZonaClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerZonaClienteCompleted(this, new ObtenerZonaClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerExistenciaCompletedEventHandler(object sender, ObtenerExistenciaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerExistenciaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerExistenciaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerZonaClienteCompletedEventHandler(object sender, ObtenerZonaClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerZonaClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerZonaClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591