'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace WSDevolucion
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSDevolucion.DevolucionSoap")>  _
    Public Interface DevolucionSoap
        
        'CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento MacAddress del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/EnviarDevolucion", ReplyAction:="*")>  _
        Function EnviarDevolucion(ByVal request As WSDevolucion.EnviarDevolucionRequest) As WSDevolucion.EnviarDevolucionResponse
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarDevolucionRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarDevolucion", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSDevolucion.EnviarDevolucionRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSDevolucion.EnviarDevolucionRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarDevolucionRequestBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public MacAddress As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=1)>  _
        Public NroDevolucion As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=2)>  _
        Public CodCliente As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=3)>  _
        Public Fecha As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=4)>  _
        Public Observaciones As String
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=5)>  _
        Public Detalle As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal MacAddress As String, ByVal NroDevolucion As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Detalle As String)
            MyBase.New
            Me.MacAddress = MacAddress
            Me.NroDevolucion = NroDevolucion
            Me.CodCliente = CodCliente
            Me.Fecha = Fecha
            Me.Observaciones = Observaciones
            Me.Detalle = Detalle
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class EnviarDevolucionResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="EnviarDevolucionResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As WSDevolucion.EnviarDevolucionResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As WSDevolucion.EnviarDevolucionResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class EnviarDevolucionResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(Order:=0)>  _
        Public EnviarDevolucionResult As Long
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal EnviarDevolucionResult As Long)
            MyBase.New
            Me.EnviarDevolucionResult = EnviarDevolucionResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface DevolucionSoapChannel
        Inherits WSDevolucion.DevolucionSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class DevolucionSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSDevolucion.DevolucionSoap)
        Implements WSDevolucion.DevolucionSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function WSDevolucion_DevolucionSoap_EnviarDevolucion(ByVal request As WSDevolucion.EnviarDevolucionRequest) As WSDevolucion.EnviarDevolucionResponse Implements WSDevolucion.DevolucionSoap.EnviarDevolucion
            Return MyBase.Channel.EnviarDevolucion(request)
        End Function
        
        Public Function EnviarDevolucion(ByVal MacAddress As String, ByVal NroDevolucion As String, ByVal CodCliente As String, ByVal Fecha As String, ByVal Observaciones As String, ByVal Detalle As String) As Long
            Dim inValue As WSDevolucion.EnviarDevolucionRequest = New WSDevolucion.EnviarDevolucionRequest()
            inValue.Body = New WSDevolucion.EnviarDevolucionRequestBody()
            inValue.Body.MacAddress = MacAddress
            inValue.Body.NroDevolucion = NroDevolucion
            inValue.Body.CodCliente = CodCliente
            inValue.Body.Fecha = Fecha
            inValue.Body.Observaciones = Observaciones
            inValue.Body.Detalle = Detalle
            Dim retVal As WSDevolucion.EnviarDevolucionResponse = CType(Me,WSDevolucion.DevolucionSoap).EnviarDevolucion(inValue)
            Return retVal.Body.EnviarDevolucionResult
        End Function
    End Class
End Namespace
