//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.18444.
// 
#pragma warning disable 1591

namespace Catalogo.LLaveClienteWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="LLaveClienteSoap", Namespace="http://tempuri.org/")]
    public partial class LLaveCliente : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback ObtenerListaPrecioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerEstadoActualOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerLLaveViajanteOperationCompleted;
        
        private System.Threading.SendOrPostCallback ObtenerLLaveCatalogoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public LLaveCliente() {
            this.Url = global::Catalogo.Properties.Settings.Default.Catalogo_LLaveClienteWS_LLaveCliente;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event ObtenerListaPrecioCompletedEventHandler ObtenerListaPrecioCompleted;
        
        /// <remarks/>
        public event ObtenerEstadoActualCompletedEventHandler ObtenerEstadoActualCompleted;
        
        /// <remarks/>
        public event ObtenerLLaveViajanteCompletedEventHandler ObtenerLLaveViajanteCompleted;
        
        /// <remarks/>
        public event ObtenerLLaveCatalogoCompletedEventHandler ObtenerLLaveCatalogoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerListaPrecio", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public byte ObtenerListaPrecio(string MacAddress, string Cuit, string IDAns) {
            object[] results = this.Invoke("ObtenerListaPrecio", new object[] {
                        MacAddress,
                        Cuit,
                        IDAns});
            return ((byte)(results[0]));
        }
        
        /// <remarks/>
        internal void ObtenerListaPrecioAsync(string MacAddress, string Cuit, string IDAns) {
            this.ObtenerListaPrecioAsync(MacAddress, Cuit, IDAns, null);
        }
        
        /// <remarks/>
        internal void ObtenerListaPrecioAsync(string MacAddress, string Cuit, string IDAns, object userState) {
            if ((this.ObtenerListaPrecioOperationCompleted == null)) {
                this.ObtenerListaPrecioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerListaPrecioOperationCompleted);
            }
            this.InvokeAsync("ObtenerListaPrecio", new object[] {
                        MacAddress,
                        Cuit,
                        IDAns}, this.ObtenerListaPrecioOperationCompleted, userState);
        }
        
        private void OnObtenerListaPrecioOperationCompleted(object arg) {
            if ((this.ObtenerListaPrecioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerListaPrecioCompleted(this, new ObtenerListaPrecioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerEstadoActual", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public byte ObtenerEstadoActual(string MacAddress, string Cuit, string IDAns) {
            object[] results = this.Invoke("ObtenerEstadoActual", new object[] {
                        MacAddress,
                        Cuit,
                        IDAns});
            return ((byte)(results[0]));
        }
        
        /// <remarks/>
        internal void ObtenerEstadoActualAsync(string MacAddress, string Cuit, string IDAns) {
            this.ObtenerEstadoActualAsync(MacAddress, Cuit, IDAns, null);
        }
        
        /// <remarks/>
        internal void ObtenerEstadoActualAsync(string MacAddress, string Cuit, string IDAns, object userState) {
            if ((this.ObtenerEstadoActualOperationCompleted == null)) {
                this.ObtenerEstadoActualOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerEstadoActualOperationCompleted);
            }
            this.InvokeAsync("ObtenerEstadoActual", new object[] {
                        MacAddress,
                        Cuit,
                        IDAns}, this.ObtenerEstadoActualOperationCompleted, userState);
        }
        
        private void OnObtenerEstadoActualOperationCompleted(object arg) {
            if ((this.ObtenerEstadoActualCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerEstadoActualCompleted(this, new ObtenerEstadoActualCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerLLaveViajante", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ObtenerLLaveViajante(string IdViajante) {
            object[] results = this.Invoke("ObtenerLLaveViajante", new object[] {
                        IdViajante});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        internal void ObtenerLLaveViajanteAsync(string IdViajante) {
            this.ObtenerLLaveViajanteAsync(IdViajante, null);
        }
        
        /// <remarks/>
        internal void ObtenerLLaveViajanteAsync(string IdViajante, object userState) {
            if ((this.ObtenerLLaveViajanteOperationCompleted == null)) {
                this.ObtenerLLaveViajanteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerLLaveViajanteOperationCompleted);
            }
            this.InvokeAsync("ObtenerLLaveViajante", new object[] {
                        IdViajante}, this.ObtenerLLaveViajanteOperationCompleted, userState);
        }
        
        private void OnObtenerLLaveViajanteOperationCompleted(object arg) {
            if ((this.ObtenerLLaveViajanteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerLLaveViajanteCompleted(this, new ObtenerLLaveViajanteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ObtenerLLaveCatalogo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public byte ObtenerLLaveCatalogo(string MacAddress, string Cuit, string IDAns, string IDViajante) {
            object[] results = this.Invoke("ObtenerLLaveCatalogo", new object[] {
                        MacAddress,
                        Cuit,
                        IDAns,
                        IDViajante});
            return ((byte)(results[0]));
        }
        
        /// <remarks/>
        internal void ObtenerLLaveCatalogoAsync(string MacAddress, string Cuit, string IDAns, string IDViajante) {
            this.ObtenerLLaveCatalogoAsync(MacAddress, Cuit, IDAns, IDViajante, null);
        }
        
        /// <remarks/>
        internal void ObtenerLLaveCatalogoAsync(string MacAddress, string Cuit, string IDAns, string IDViajante, object userState) {
            if ((this.ObtenerLLaveCatalogoOperationCompleted == null)) {
                this.ObtenerLLaveCatalogoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnObtenerLLaveCatalogoOperationCompleted);
            }
            this.InvokeAsync("ObtenerLLaveCatalogo", new object[] {
                        MacAddress,
                        Cuit,
                        IDAns,
                        IDViajante}, this.ObtenerLLaveCatalogoOperationCompleted, userState);
        }
        
        private void OnObtenerLLaveCatalogoOperationCompleted(object arg) {
            if ((this.ObtenerLLaveCatalogoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ObtenerLLaveCatalogoCompleted(this, new ObtenerLLaveCatalogoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerListaPrecioCompletedEventHandler(object sender, ObtenerListaPrecioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerListaPrecioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerListaPrecioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerEstadoActualCompletedEventHandler(object sender, ObtenerEstadoActualCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerEstadoActualCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerEstadoActualCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerLLaveViajanteCompletedEventHandler(object sender, ObtenerLLaveViajanteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerLLaveViajanteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerLLaveViajanteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    public delegate void ObtenerLLaveCatalogoCompletedEventHandler(object sender, ObtenerLLaveCatalogoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.18408")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ObtenerLLaveCatalogoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ObtenerLLaveCatalogoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public byte Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((byte)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591