'------------------------------------------------------------------------------
' <auto-generated>
'     Este código fue generado por una herramienta.
'     Versión de runtime:4.0.30319.18444
'
'     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
'     se vuelve a generar el código.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.Data

Namespace WSUpdateClientes
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="WSUpdateClientes.UpdateClientesSoap")>  _
    Public Interface UpdateClientesSoap
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTodosLosClientes_Cantidad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetTodosLosClientes_Cantidad(ByVal MacAddress As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTodosLosClientes_Datos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetTodosLosClientes_Datos(ByVal MacAddress As String, ByVal LastID As Long) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTodosLosClientes_Datos_Registros", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetTodosLosClientes_Datos_Registros(ByVal MacAddress As String, ByVal LastID As Long) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTodasLasCtasCtes_Cantidad", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetTodasLasCtasCtes_Cantidad(ByVal MacAddress As String) As Long
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTodasLasCtasCtes_Datos", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetTodasLasCtasCtes_Datos(ByVal MacAddress As String, ByVal LastID As Long) As String
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetTodasLasCtasCtes_Datos_Registros", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Function GetTodasLasCtasCtes_Datos_Registros(ByVal MacAddress As String, ByVal LastID As Long) As System.Data.DataSet
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SincronizacionClientesCompletada", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub SincronizacionClientesCompletada(ByVal MacAddress As String)
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/SincronizacionCtasCtesCompletada", ReplyAction:="*"),  _
         System.ServiceModel.XmlSerializerFormatAttribute()>  _
        Sub SincronizacionCtasCtesCompletada(ByVal MacAddress As String)
    End Interface
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface UpdateClientesSoapChannel
        Inherits WSUpdateClientes.UpdateClientesSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class UpdateClientesSoapClient
        Inherits System.ServiceModel.ClientBase(Of WSUpdateClientes.UpdateClientesSoap)
        Implements WSUpdateClientes.UpdateClientesSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        Public Function GetTodosLosClientes_Cantidad(ByVal MacAddress As String) As Long Implements WSUpdateClientes.UpdateClientesSoap.GetTodosLosClientes_Cantidad
            Return MyBase.Channel.GetTodosLosClientes_Cantidad(MacAddress)
        End Function
        
        Public Function GetTodosLosClientes_Datos(ByVal MacAddress As String, ByVal LastID As Long) As String Implements WSUpdateClientes.UpdateClientesSoap.GetTodosLosClientes_Datos
            Return MyBase.Channel.GetTodosLosClientes_Datos(MacAddress, LastID)
        End Function
        
        Public Function GetTodosLosClientes_Datos_Registros(ByVal MacAddress As String, ByVal LastID As Long) As System.Data.DataSet Implements WSUpdateClientes.UpdateClientesSoap.GetTodosLosClientes_Datos_Registros
            Return MyBase.Channel.GetTodosLosClientes_Datos_Registros(MacAddress, LastID)
        End Function
        
        Public Function GetTodasLasCtasCtes_Cantidad(ByVal MacAddress As String) As Long Implements WSUpdateClientes.UpdateClientesSoap.GetTodasLasCtasCtes_Cantidad
            Return MyBase.Channel.GetTodasLasCtasCtes_Cantidad(MacAddress)
        End Function
        
        Public Function GetTodasLasCtasCtes_Datos(ByVal MacAddress As String, ByVal LastID As Long) As String Implements WSUpdateClientes.UpdateClientesSoap.GetTodasLasCtasCtes_Datos
            Return MyBase.Channel.GetTodasLasCtasCtes_Datos(MacAddress, LastID)
        End Function
        
        Public Function GetTodasLasCtasCtes_Datos_Registros(ByVal MacAddress As String, ByVal LastID As Long) As System.Data.DataSet Implements WSUpdateClientes.UpdateClientesSoap.GetTodasLasCtasCtes_Datos_Registros
            Return MyBase.Channel.GetTodasLasCtasCtes_Datos_Registros(MacAddress, LastID)
        End Function
        
        Public Sub SincronizacionClientesCompletada(ByVal MacAddress As String) Implements WSUpdateClientes.UpdateClientesSoap.SincronizacionClientesCompletada
            MyBase.Channel.SincronizacionClientesCompletada(MacAddress)
        End Sub
        
        Public Sub SincronizacionCtasCtesCompletada(ByVal MacAddress As String) Implements WSUpdateClientes.UpdateClientesSoap.SincronizacionCtasCtesCompletada
            MyBase.Channel.SincronizacionCtasCtesCompletada(MacAddress)
        End Sub
    End Class
End Namespace
