//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Catalogo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsOracle/VerExistencia.asmx")]
        public string Catalogo_VerExistenciaWS_VerExistencia {
            get {
                return ((string)(this["Catalogo_VerExistenciaWS_VerExistencia"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/UpdateClientes.asmx")]
        public string Catalogo_UpdateClientesWS_UpdateClientes {
            get {
                return ((string)(this["Catalogo_UpdateClientesWS_UpdateClientes"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/appConfig.asmx")]
        public string Catalogo_AppConfigWS_appConfig {
            get {
                return ((string)(this["Catalogo_AppConfigWS_appConfig"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/LLaveCliente.asmx")]
        public string Catalogo_LLaveClienteWS_LLaveCliente {
            get {
                return ((string)(this["Catalogo_LLaveClienteWS_LLaveCliente"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/audit_v_304.asmx")]
        public string Catalogo_AuditWS_audit_v_304 {
            get {
                return ((string)(this["Catalogo_AuditWS_audit_v_304"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/ClientesNovedades.asmx")]
        public string Catalogo_ClientesNovedadesWs_ClientesNovedades {
            get {
                return ((string)(this["Catalogo_ClientesNovedadesWs_ClientesNovedades"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/Devolucion.asmx")]
        public string Catalogo_DevolucionWS_Devolucion {
            get {
                return ((string)(this["Catalogo_DevolucionWS_Devolucion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/InterDeposito.asmx")]
        public string Catalogo_InterDepositoWS_InterDeposito {
            get {
                return ((string)(this["Catalogo_InterDepositoWS_InterDeposito"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/Pedidos.asmx")]
        public string Catalogo_PedidosWS_Pedidos {
            get {
                return ((string)(this["Catalogo_PedidosWS_Pedidos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/Recibos_v_303.asmx")]
        public string Catalogo_RecibosWS_Recibos_v_303 {
            get {
                return ((string)(this["Catalogo_RecibosWS_Recibos_v_303"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://190.3.78.12/wsCatalogo4/Rendicion.asmx")]
        public string Catalogo_RendicionWS_Rendicion {
            get {
                return ((string)(this["Catalogo_RendicionWS_Rendicion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=\"C:\\Catalogo ANS\\Datos\\catalogo.mdb\"" +
            ";Password=video80min;User ID=inVent;Jet OLEDB:System database=C:\\Windows\\Help\\kb" +
            "appcat.hlp")]
        public string catalogoConnectionString {
            get {
                return ((string)(this["catalogoConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Provider=Microsoft.Jet.OLEDB.4.0;Data Source=|DataDirectory|\\catalogo.mdb;Passwor" +
            "d=video80min;User ID=inVent;Jet OLEDB:System database=C:\\Windows\\Help\\kbappcat.h" +
            "lp")]
        public string catalogoConnectionString1 {
            get {
                return ((string)(this["catalogoConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.autonauticasur-r.com.ar/Catalogo/Info.asmx?wsdl")]
        public string Catalogo_CatalogoWS_Info {
            get {
                return ((string)(this["Catalogo_CatalogoWS_Info"]));
            }
        }
    }
}
